server:
  port: 33207

spring:
  config:
    activate:
      on-profile: test

crawl:
  naver:
    url: "https://m.stock.naver.com/domestic/index/KOSPI/total"

database:
  datasource:
    batch:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/BATCH?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/BATCH?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    log:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    pub:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    cocoin:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    mattermost:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    news:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    coin:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    webhook:
      master:
        url: jdbc:mysql://kimd0.iptime.org:13306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:13306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000